- name: ensure jupyterhub database is created
  postgresql_db: name={{dbname}}
  become: yes
  become_user: postgres

- name: ensure user has access to database
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
  become: yes
  become_user: postgres

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
  become: yes
  become_user: postgres

- name: ensure no other user can access the database
  postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent
  become: yes
  become_user: postgres
